apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: tensorleap-pysvcs
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tensorleap-pysvcs
  minReplicas: 1
  maxReplicas: 5
  # metrics:
  # - external:
  #     metricName: pubsub.googleapis.com|subscription|num_undelivered_messages
  #     metricSelector:
  #       matchLabels:
  #         resource.labels.subscription_id: echo-read
  #     targetAverageValue: "2"
  #   type: External
  # scaleTargetRef:
  #   apiVersion: apps/v1
  #   kind: Deployment
  #   name: pubsub
