apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    targetRevision: 7.6.1
    chart: elasticsearch
    helm:
      values: |

        clusterName: "elasticsearch"
        nodeGroup: "master"
        nodeSelector:
          cloud.google.com/gke-nodepool: elastic-pool
  destination:
    namespace: dev-data
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
