apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    targetRevision: 7.6.1
    chart: kibana
    helm:
      parameters:
        # - name: ingress.hosts[0]
        #   value: app.tensorleap.ai
        # - name: ingress.enabled
        #   value: "true"
        # - name: ingress.path
        #   value: /kibana*
        - name: service.type
          value: NodePort
      values: |

        healthCheckPath: "/kibana/app/kibana"
        kibanaConfig: 
          kibana.yml: |
            server:
              basePath: /kibana
              rewriteBasePath: true
        elasticsearchHosts: "http://elasticsearch-master.dev-data:9200"
        nodeSelector:
          cloud.google.com/gke-nodepool: elastic-pool
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
