apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  group: dev-infra
  variant: dev

commonAnnotations:
  environment: dev
  group: dev-services

resources:
  - ../../../base/infra/dev

patchesStrategicMerge:
  - patches/infra-dev-secrets.yaml
  - patches/clusterIssuer-letsencrypt-prod.yaml
  - elasticsearch.yaml
  - kibana.yaml
  - mongodb.yaml
  - ci-nfs-server-provisioner.yaml
