apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./service.yaml
  - ./ingress.yaml
  - ./deployment.yaml

images:
  - name: gcr.io/tensorleap-dev-3/web-app
    newTag: latest
