apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: development
  namespace: argocd
  labels:
    group: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:tensorleap/infra.git
    path: argo/cd/overlays/apps/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
