apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - hpa.yaml
  - env-configmap.yaml
  - pvc.yaml
#   - name: node-server-files-configmap
#     files:
#       - configs/development.json
#   - name: node-server-env-configmap
#     literals:
#       - LOG_LEVEL=info
#       - NODE_ENV=production
#       - PUBSUB_PREFIX="_prod"
