apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  labels:
    group: ci-cd
spec:
  project: default
  source:
    repoURL: git@github.com:tensorleap/infra.git
    path: argo/cd/overlays/infra/shared/argo-events
  destination:
    namespace: argo-events
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
