apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tensorleap-doc
  labels:
    group: infra-shared
spec:
  project: default
  source:
    repoURL: git@github.com:tensorleap/infra.git
