---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
spec: {}
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
spec: {}
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
spec: {}
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: shared-data
spec: {}
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-workflows
spec: {}
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo
spec: {}
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: custom-metrics
spec: {}
status: {}
