apiVersion: v1
kind: Service
metadata:
  name: workflow-controller-metrics
spec:
  ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: workflow-controller
