apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-shared
  namespace: argocd
  labels:
    group: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:tensorleap/infra.git
    path: argo/cd/overlays/infra/shared
  destination:
    server: https://kubernetes.default.svc
    namespace: "*"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
