apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  group: dev-infra
  variant: dev

commonAnnotations:
  environment: dev
  group: dev-services

resources:
  - rbac.yaml
  - deployment.yaml
  - service.yaml
