apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  variant: dev

commonAnnotations:
  note: Development Environment

resources:
  # any shared resources
  - ../../../base/apps/dev
  # dev specific applications (not to be confused with infra)
  - web-app.yaml
  - node-server.yaml
  - tensorleap.yaml
  # - python-cpu.yaml
  # - python-gpu.yaml

patchesStrategicMerge:
  - ingress.yaml

namespace: argocd
