apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tensorleap
  namespace: argocd
  labels:
    group: Backend
spec:
  project: default
  source:
    repoURL: git@github.com:tensorleap/infra.git
    path: argo/cd/overlays/apps/dev/tensorleap
    # targetRevision: master
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
