apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
  - patches/argo-server-service.yaml
  - patches/argo-server-ingress.yaml

resources:
  - ../../../../base/infra/shared/argo-workflows

namespace: argo
