apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: infra-dev-secrets
  namespace: dev-data
data:
  mongodb-root-password: dGVuc29ybGVhcA==
  mongodb-password: dGVuc29ybGVhcA==
  mongodb-replica-set-key: dGVuc29ybGVhcA==
