apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- patches/service.yaml
- patches/ingress.yaml
- patches/deployment.yaml
  # - patches/files-configmap.yaml

resources:
- ../../../../base/apps/dev/web-app

namespace: dev
images:
- name: gcr.io/tensorleap-dev-3/web-app
  newTag: fc64b9a
